# Generated by Django 3.2.10 on 2022-11-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trafficdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now=True, max_length=200)),
                ('db_val', models.FloatField(max_length=200)),
                ('light_stat', models.CharField(max_length=200)),
                ('timeout', models.IntegerField(default=3000)),
                ('timeout_inc', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('node_id', 'timestamp')},
            },
        ),
    ]
