# Generated by Django 3.2.10 on 2022-11-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ML', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficdata',
            name='light_stat',
            field=models.CharField(default='GREEN', max_length=200),
        ),
    ]
